- name: (qemu) install packages
  tags:
    - qemu
    - include
  ansible.builtin.include_tasks:
    file: arch.yml
  when: ansible_os_family == "Archlinux"

- name: (qemu) install packages
  tags:
    - qemu
    - include
  ansible.builtin.include_tasks:
    file: void.yml
  when: ansible_os_family == "Void"


