- name: include tasks
  tags:
    - qemu
    - include
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution|lower }}.yml"

- name: (qemu) enable and start network default
  become: true
  tags:
    - qemu
    - system
  ansible.builtin.shell:
    cmd: |
      virsh net-start default
      virsh net-autostart default
