- name: (qemu) install qemu-libvirt
  tags:
    - qemu
    - include
  ansible.builtin.include_tasks:
    file: qemu.yml

- name: (qemu) install quickemu
  tags:
    - quickemu
    - include
  ansible.builtin.include_tasks:
    file: quickemu.yml


