- name: (qemu) install qemu packages
  tags:
    - qemu
    - packages
  community.general.zypper:
    name: "{{ item }}"
    state: latest
  loop:
    - libvirt
    - qemu
    - virt-manager
    - libvirt-daemon-driver-qemu 
    - qemu-kvm

- name: (qemu)
  tags:
    - qemu
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: 
      - libvirt
      - kvm
    append: true

- name: (qemu) enable and start neccessary services
  tags:
    - qemu
    - system
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - libvirtd

- name: (qemu) enable and start network default
  become: true
  tags:
    - qemu
    - system
  ansible.builtin.shell:
    cmd: |
      virsh net-start default
      virsh net-autostart default
