- name: (qemu) install qemu packages
  tags:
    - qemu
    - packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - qemu-kvm
    - qemu-system
    - qemu-utils
    - python3
    - python3-pip
    - libvirt-clients
    - libvirt-daemon-system
    - bridge-utils
    - virtinst
    - libvirt-daemon
    - virt-manager

- name: (qemu)
  tags:
    - qemu
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: 
      - libvirt
      - kvm
    append: true

- name: (qemu) enable and start neccessary services
  tags:
    - qemu
    - system
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - libvirtd
