- name: (suckless) install packages
  tags:
    - suckless
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - base-devel
    - libx11
    - libxft
    - libxinerama
    - freetype2
    - ttf-jetbrains-mono-nerd
    - ttf-iosevka-nerd
