- name: install suckless dependencies
  tags:
    - suckless
    - packages
  community.general.pacman:
    name:
      - base-devel
      - libx11
      - libxft
      - libxinerama
      - freetype2
      - ttf-jetbrains-mono-nerd
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: Ensure source directory exists
  become: false
  tags:
    - suckless
    - packages
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.local/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: copy source files to ~/.local/src
  become: false
  tags:
    - suckless
    - packages
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.local/src
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - dwm
    - st
    - dmenu

- name: compile suckless software
  become: true
  tags:
    - suckless
    - packages
  shell: "make clean install"
  args:
    chdir: "/home/{{ ansible_user }}/.local/src/{{ item }}"
  loop:
    - dwm
    - st
    - dmenu

- name: copy the .desktop file to /usr/share/applications/
  become: true
  tags:
    - suckless
    - files
  ansible.builtin.copy:
    src: dwm.desktop
    dest: /usr/share/applications/dwm.desktop
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
