- name: (suckless) include archlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: arch.yml
  when: ansible_os_family == "Archlinux"

- name: (suckless) include voidlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: void.yml
  when: ansible_os_family == "Void"

- name: (suckless) remove src files
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.local/src
    state: absent

- name: (suckless) create src directory
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.local/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (suckless) copy src files
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.local/src
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - dwm
    - dmenu
    - st

- name: (suckless) compile src files
  become: true
  tags:
    - suckless
    - files
  shell: "make clean install"
  args:
    chdir: "/home/{{ ansible_user }}/.local/src/{{ item }}"
  loop:
    - dwm
    - dmenu
    - st
