- name: (suckless@voidlinux) install packages
  tags:
    - suckless
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
    upgrade: true
  loop:
    - base-devel
    - libX11-devel
    - libXft-devel
    - libXinerama-devel
    - harfbuzz-devel
    - freetype
