- name: install suckless dependencies
  tags:
    - suckless
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - base-devel
    - libX11-devel
    - libXft-devel
    - libXinerama-devel
    - harfbuzz-devel
    - freetype

- name: setup ttf-iosevka-nerd on voidlinux
  become: true
  tags:
    - suckless
    - custom
    - packages
  ansible.builtin.shell:
    cmd: |
      cd /tmp
      curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Iosevka.zip
      unzip Iosevka.zip -d Iosevka
      cp -r Iosevka /usr/share/fonts

- name: setup ttf-jetbrains-mono-nerd on voidlinux
  become: true
  tags:
    - suckless
    - custom
    - packages
  ansible.builtin.shell:
    cmd: |
      cd /tmp
      curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
      unzip JetBrainsMono.zip -d JetBrainsMono
      cp -r JetBrainsMono /usr/share/fonts

- name: remove ~/.local/src directory
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.local/src
    state: absent

- name: Ensure source directory exists
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.local/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: copy source files to ~/.local/src
  become: false
  tags:
    - suckless
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.local/src
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - dwm
    - dmenu
    - st

- name: compile suckless software
  become: true
  tags:
    - suckless
    - files
  shell: "make clean install"
  args:
    chdir: "/home/{{ ansible_user }}/.local/src/{{ item }}"
  loop:
    - dwm
    - dmenu
    - st
