- name: install build dependencies
  tags:
    - libreoffice
  community.general.pacman:
    state: latest
    name:
      - git
      - ccache
      - ant
      - apr
      - beanshell
      - bluez-libs
      - clucene
      - coin-or-mp
      - cppunit
      - curl
      - dbus-glib
      - desktop-file-utils
      - doxygen
      - flex
      - gcc-libs
      - gdb
      - glm
      - gobject-introspection
      - gperf
      - gpgme
      - graphite
      - gst-plugins-base-libs
      - gtk3
      - harfbuzz-icu
      - hicolor-icon-theme
      - hunspell
      - hyphen
      - icu
      - java-environment
      - junit
      - lcms2
      - libabw
      - libatomic_ops
      - libcdr
      - libcmis
      - libe-book
      - libepoxy
      - libepubgen
      - libetonyek
      - libexttextcat
      - libfreehand
      - libgl
      - libjpeg
      - liblangtag
      - libmspub
      - libmwaw
      - libmythes
      - libnumbertext
      - libodfgen
      - liborcus
      - libpagemaker
      - libqxp
      - libstaroffice
      - libtommath
      - libvisio
      - libwpd
      - libwpg
      - libwps
      - libxinerama
      - libxrandr
      - libxslt
      - libzmf
      - lpsolve
      - mariadb-libs
      - mdds
      - nasm
      - neon
      - nspr
      - nss
      - pango
      - plasma-framework5
      - poppler
      - postgresql-libs
      - python
      - qt5-base
      - redland
      - sane
      - serf
      - sh
      - shared-mime-info
      - ttf-liberation
      - unixodbc
      - unzip
      - xmlsec
      - zip
      - gtk4
      - qt6-base
      - zxing-cpp
      - abseil-cpp

- name: setup ccache with cache size of 150G
  become: false
  tags:
    - libreoffice
  ansible.builtin.shell:
    cmd: ccache --max-size 150G

- name: clone the core repository
  become: false
  tags:
    - libreoffice
  ansible.builtin.git:
    repo: https://gerrit.libreoffice.org/core
    dest: /home/{{ ansible_user }}/repos/libreoffice
    update: false

- name: copy autogen.input to core repo
  become: false
  tags:
    - libreoffice
  ansible.builtin.copy:
    src: autogen.input
    dest: /home/{{ ansible_user }}/repos/libreoffice/autogen.input
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: build libreoffice
  become: false
  tags:
    - libreoffice
  ansible.builtin.shell:
    chdir: /home/{{ ansible_user }}/repos/libreoffice
    cmd: ./autogen.sh && make

- name: setup neovim as editor
  become: false
  tags:
    - libreoffice
  ansible.builtin.shell:
    chdir: /home/{{ ansible_user }}/repos/libreoffice
    cmd: make vim-ide-integration

- name: setup qtcreator as debugger
  become: false
  tags:
    - libreoffice
  ansible.builtin.shell:
    chdir: /home/{{ ansible_user }}/repos/libreoffice
    cmd: make qtcreator-ide-integration
