- name: ensure config directory exists
  become: false
  tags:
    - mpv
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/mpv"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: copy config files to ~/.config/mpv
  become: false
  tags:
    - mpv
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.config/mpv/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - input.conf
    - mpv.conf
