- name: (mpv) install packages
  tags:
    - mpv
    - packages
  community.general.zypper:
    name: "{{ item }}"
    state: latest
  loop:
    - mpv

- name: (mpv) create config directory
  become: false
  tags:
    - mpv
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/mpv"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (mpv) create config directory
  become: false
  tags:
    - mpv
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.config/mpv/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - input.conf
    - mpv.conf

- name: (mpv) save config directory
  become: false
  tags:
    - save
    - save-mpv
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/mpv/{{ item }}
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/mpv/files/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  loop:
    - input.conf
    - mpv.conf
