#!/bin/env bash

function initVoid() {
    sudo cp /usr/share/xbps.d/00-repository-main.conf /etc/xbps.d/00-repository-main.conf
    sudo xbps-install -Syu xbps
    sudo xbps-install -Syu git openssl ansible python3-watchdog neovim
}

cloneDotfiles() {
    mkdir -p $HOME/repos && cd $HOME/repos
    [ ! -d "$HOME/repos/dotfiles" ] && git clone https://codeberg.org/printfdebugging/dotfiles.git $HOME/repos/dotfiles
    cd $HOME/repos/dotfiles
}

function runAnsibleTasksWithVaultPass() {
    ansible-playbook main.yml --tags "${@}" --become --ask-become-pass --ask-vault-pass
}

function runAnsibleSaveTask() {
    # save-* tagged tasks neither use any vault string nor have become: true
    ansible-playbook main.yml --tags "${@}"
}

[ ! $(command -v ansible-playbook) ] && initVoid || echo "found ansible-playbook"
cloneDotfiles

case "$1" in 
    "")         runAnsibleTasksWithVaultPass $(ls ./roles | xargs | sed 's/\s\+/,/g') ;;
    "save-"*)   runAnsibleSaveTask ${@};;
    *)          runAnsibleTasksWithVaultPass ${@};;
esac
