---
- hosts: all
  roles:
    - creds
    - git
    - awesome
    - base
    - bin
    - ccache
    - chromium
    - cool
    - dunst
    - emacs
    - flameshot
    - fonts
    - gtimelog
    - gtk
    - libreoffice-dev
    - mpv
    - neovim
    - okular
    - qemu
    - services
    - suckless
    - tmux
    - user
    - wallpapers
    - xorg
    - yt-dlp
    - zsh
