---
- hosts: all
  become: true
  pre_tasks:
    - name: "Update Cache"
      ansible.builtin.package:
        update_cache: true

- hosts: linux-machines
  roles:
    - ssh
    - git
    - base
    - alacritty
    - awesome
    - bin
    - dunst
    - emacs
    - flameshot
    - git
    - gtk-3.0
    - mpv
    - neovim
    - suckless
    - tmux
    - wallpapers
    - xorg
    - yt-dlp
    - zsh

- hosts: developement-machines
  roles:
    - developement
