#!/bin/bash

GRN='\033[1;32m'
CYN='\033[1;36m'
CLR='\033[0m'

function packages() {
    sudo pacman -S --noconfirm \
        'abseil-cpp' \
        'ansible' \
        'nginx' \
        'ant' \
        'apr' \
        'base-devel' \
        'bazelisk' \
        'swtpm' \
        'chafa' \
        'ninja' \
        'stylua' \
        'beanshell' \
        'blender' \
        'pass' \
        'pass-otp' \
        'pam' \
        'zbar' \
        'blueman' \
        'bluez' \
        'bluez-libs' \
        'breeze' \
        'breeze-icons' \
        'breeze-gtk' \
        'bridge-utils' \
        'btop' \
        'cargo' \
        'cbatticon' \
        'ccache' \
        'chromium' \
        'clang' \
        'clucene' \
        'cmake' \
        'coin-or-mp' \
        'cppunit' \
        'ctags' \
        'curl' \
        'dbus-glib' \
        'shellcheck' \
        'desktop-file-utils' \
        'dnsmasq' \
        'docker' \
        'docker-compose' \
        'doxygen' \
        'dunst' \
        'ebtables' \
        'extra-cmake-modules' \
        'fastfetch' \
        'fd' \
        'feh' \
        'figlet' \
        'flameshot' \
        'flex' \
        'fontconfig' \
        'freetype2' \
        'fzf' \
        'gcc-libs' \
        'gdb' \
        'gdk-pixbuf2' \
        'gimp' \
        'git' \
        'glade' \
        'glm' \
        'go' \
        'gobject-introspection' \
        'gperf' \
        'gpgme' \
        'graphite' \
        'gst-plugins-base-libs' \
        'gtk3' \
        'gtk4' \
        'gvfs' \
        'gvfs-mtp' \
        'harfbuzz' \
        'harfbuzz-icu' \
        'hicolor-icon-theme' \
        'hunspell' \
        'hyphen' \
        'i3lock' \
        'icu' \
        'inkscape' \
        'iptables' \
        'java-environment' \
        'jdk-openjdk' \
        'jre21-openjdk' \
        'junit' \
        'lcms2' \
        'lib32-libcap' \
        'libabw' \
        'libatomic_ops' \
        'libcap' \
        'libcap-ng' \
        'libcdr' \
        'libcmis' \
        'libe-book' \
        'libepoxy' \
        'libepubgen' \
        'libetonyek' \
        'libexttextcat' \
        'libfreehand' \
        'libgl' \
        'libguestfs' \
        'libjpeg' \
        'liblangtag' \
        'libmspub' \
        'libmwaw' \
        'libmythes' \
        'libnma' \
        'libnumbertext' \
        'libodfgen' \
        'liborcus' \
        'libpagemaker' \
        'libpng' \
        'libqxp' \
        'libreoffice' \
        'libstaroffice' \
        'libtommath' \
        'libvisio' \
        'libwpd' \
        'libwpg' \
        'libwps' \
        'libx11' \
        'libxft' \
        'libxinerama' \
        'libxrandr' \
        'libxslt' \
        'libxxf86vm' \
        'libzmf' \
        'lld' \
        'loupe' \
        'lpsolve' \
        'lua' \
        'luarocks' \
        'lxappearance' \
        'man-db' \
        'man-pages' \
        'mariadb-libs' \
        'mdds' \
        'meson' \
        'mpv' \
        'mtpfs' \
        'nasm' \
        'neon' \
        'neovim' \
        'netcat' \
        'networkmanager' \
        'network-manager-applet' \
        'nodejs' \
        'npm' \
        'nspr' \
        'nss' \
        'ntfs-3g' \
        'obs-studio' \
        'okular' \
        'openbsd-netcat' \
        'pango' \
        'pasystray' \
        'pavucontrol' \
        'perf' \
        'plasma-framework5' \
        'poco' \
        'poppler' \
        'postgresql-libs' \
        'pulseaudio' \
        'pyright' \
        'python' \
        'python-lxml' \
        'python-pip' \
        'python-polib' \
        'python-watchdog' \
        'qemu' \
        'qt5-base' \
        'qt6ct' \
        'qt6-base' \
        'redland' \
        'ripgrep' \
        'ruff' \
        'sane' \
        'seahorse' \
        'serf' \
        'sh' \
        'shaderc' \
        'shared-mime-info' \
        'sxiv' \
        'thunar' \
        'thunar-media-tags-plugin' \
        'thunar-shares-plugin' \
        'webp-pixbuf-loader' \
        'thunar-volman' \
        'thunderbird' \
        'tigervnc' \
        'tlp' \
        'tmux' \
        'ttf-liberation' \
        'ttf-jetbrains-mono-nerd' \
        'ttf-iosevka-nerd' \
        'noto-fonts' \
        'tumbler' \
        'ueberzug' \
        'unixodbc' \
        'unzip' \
        'valgrind' \
        'vde2' \
        'vinagre' \
        'virt-manager' \
        'virt-viewer' \
        'vscode' \
        'vulkan-radeon' \
        'vulkan-tools' \
        'wget' \
        'xclip' \
        'xcompmgr' \
        'xdotool' \
        'xf86-input-libinput' \
        'xf86-video-amdgpu' \
        'xf86-video-ati' \
        'xmlsec' \
        'xorg-server' \
        'xorg-setxkbmap' \
        'xorg-xauth' \
        'xorg-xinit' \
        'xorg-xprop' \
        'xorg-xrandr' \
        'xorg-xset' \
        'xsel' \
        'xwallpaper' \
        'yarn' \
        'yt-dlp' \
        'zip' \
        'zola' \
        'zsh' \
        'zsh-autosuggestions' \
        'zsh-completions' \
        'zsh-syntax-highlighting' \
        'opengl-man-pages' \
        'zxing-cpp'
}

function aur() {
    if ! which yay >/dev/null 2>&1; then
        mkdir -p "$HOME/.local/src" && cd "$HOME/.local/src" || exit 1
        git clone https://aur.archlinux.org/yay-bin.git >/dev/null 2>&1
        cd yay-bin && makepkg -si --noconfirm >/dev/null 2>&1
    fi

    yay -Sy --noconfirm \
        'brave-bin' \
        'pam-gnupg' \
        'par' \
        'gtypist'
}

function services() {
    sudo systemctl enable --now \
        'bluetooth.service' \
        'nginx.service' \
        'blueman-mechanism.service' \
        'libvirtd.service' \
        'docker.service' \
        'tlp.service'
}

function groups() {
    groups=(
        'libvirt'
        'kvm'
        'docker'
    )
    # append user to groups
    for group in "${groups[@]}"; do
        sudo usermod -aG "$group" "$(whoami)"
    done
}

# call after setup_drives
function git() {
    git_repositories=(
        # various dotfiles attempts
        'https://github.com/printfdebugging/dotfiles'
        'https://github.com/printfdebugging/pkgbuild-like-dotfiles'
        'https://github.com/printfdebugging/dots'

        # private writings
        'https://github.com/printfdebugging/logs'
        'https://github.com/printfdebugging/journal'

        # window manager and scripts
        'https://github.com/printfdebugging/bin'
        'https://github.com/printfdebugging/dwm'
        'https://github.com/printfdebugging/st'
        'https://github.com/printfdebugging/dmenu'

        # graphics programming projects
        'https://github.com/printfdebugging/sfml-blueprints'
        'https://github.com/printfdebugging/skia'
        'https://github.com/printfdebugging/learn-opengl'
        'https://github.com/printfdebugging/layman'

        # books
        'https://github.com/printfdebugging/unix-network-programming'

        # misc software projects
        'https://github.com/printfdebugging/whiteboard'
        'https://github.com/printfdebugging/chat'
        'https://github.com/printfdebugging/chronophage'
        'https://github.com/printfdebugging/music-player'
        'https://github.com/printfdebugging/neat-search-results'

        # nvim plugins
        'https://github.com/printfdebugging/chat.nvim'
        'https://github.com/printfdebugging/mail.nvim'

        # gitlab projects
        'https://gitlab.com/printfdebugging/website'

        # libreoffice projects
        'https://github.com/printfdebugging/themes'
        'https://github.com/printfdebugging/keybindings'
        'https://gerrit.libreoffice.org/core'
        'https://github.com/CollaboraOnline/online'

        # other intersting projects from the internet
        'https://github.com/glfw/glfw'
        'https://github.com/nicbarker/clay'
        'https://github.com/pongasoft/emscripten-glfw'
        'https://github.com/TinyCC/tinycc'
        'https://github.com/nginx/nginx'
        'https://github.com/nitrix/glad'
        'https://github.com/universal-ctags/ctags'
        'https://github.com/mpv-player/mpv'
        'https://github.com/fogleman/Craft'
        'https://github.com/antirez/kilo'
        'https://github.com/skx/kilua'
        'https://github.com/bakkeby/dwm-commented'
    )
    # clone git repositories
    for repository in "${git_repositories[@]}"; do
        projects_dir="/media/projects"
        repo_name="$(echo "$repository" | sed 's#.*/##')"
        if ! [ -d "$projects_dir/$repo_name" ]; then
            echo -e "${CYN}==>${CLR} cloning $repo_name"
            git clone "$repository" "$projects_dir/$repo_name" >/dev/null 2>&1
        fi
    done
}

function suckless() {
    suckless_projects=(
        'dwm'
        'st'
        'dmenu'
    )
    # clone and build suckless
    for suckless in "${suckless_projects[@]}"; do
        suckless_dir="/media/projects/$suckless"
        if ! [ -d "$suckless_dir" ]; then
            git clone "https://github.com/printfdebugging/$suckless.git" "$suckless_dir"
        fi

        echo -e "$CYN==>$CLR compiling $GRN$suckless$CLR"
        sudo make -C "$suckless_dir" install >/dev/null 2>&1
    done
}

function browser() {
    chromium_extensions=(
        'bhlhnicpbhignbdhedgjhgdocnmhomnp'
        'cjpalhdlnbpafiamejdnhcphjbkeiagm'
        'dbepggeogbaibhgnhhndojpepiihcmeb'
        'dpjamkmjmigaoobjbekmfgabipmfilij'
        'eimadpbcbfnmbkopoojfekhnkhdbieeh'
        'kchgllkpfcggmdaoopkhlkbcokngahlg'
    )
    # create the extension files
    for extension in "${chromium_extensions[@]}"; do
        if ! [ -f "/usr/share/chromium/extensions/$extension.json" ]; then
            sudo mkdir -p "/usr/share/chromium/extensions/"
            echo '{ "external_update_url": "https://clients2.google.com/service/update2/crx" }' | sudo tee "/usr/share/chromium/extensions/$extension.json" >/dev/null 2>&1
        fi
    done
}

function neovim() {
    mkdir -p "$HOME/.config/nvim/"
    cp ./init.lua "$HOME/.config/nvim/"
}

function passwords() {
    if ! [ -d "$HOME/.password-store" ]; then
        echo -e "${CYN}==>${CLR} cloning .password-store"
        git clone git@github.com:printfdebugging/password-store "$HOME/.password-store" >/dev/null 2>&1
    fi

    if ! [ -f "$HOME/.password-store/.git/hooks/post-commit" ]; then
        echo -e "${CYN}==>${CLR} installing post-commit hook"
        printf "#\!/bin/bash\n\ngit push" | tee "$HOME/.password-store/.git/hooks/post-commit" >/dev/null 2>&1
    fi
}

function pam() {
    system_login_file="/etc/pam.d/system-local-login"
    if [ -f "$system_login_file" ]; then
        lines=(
            'auth     optional  pam_gnupg.so store-only'
            'session  optional  pam_gnupg.so'
        )
        for line in "${lines[@]}"; do
            if [ "$(grep -c "$line" "$system_login_file")" -eq 0 ]; then
                echo "$line" | sudo tee -a "$system_login_file" >/dev/null 2>&1
            fi
        done
    else
        echo "$system_login_file file not found" && exit 1
    fi

    i3lock_file="/etc/pam.d/i3lock"
    if [ -f "$i3lock_file" ]; then
        lines=(
            'auth     optional  pam_gnupg.so'
        )
        for line in "${lines[@]}"; do
            if [ "$(grep -c "$line" "$i3lock_file")" -eq 0 ]; then
                echo "$line" | sudo tee -a "$i3lock_file" >/dev/null 2>&1
            fi
        done
    else
        echo "$i3lock_file file not found" && exit 1
    fi
}

function disable_kwallet() {
    mkdir -p "$HOME/.config/"
    cp ./kwalletrc "$HOME/.config/kwalletrc"
}

function mimeapps() {
    mkdir -p "$HOME/.config/nvim/"
    mkdir -p "$HOME/.local/share/applications"
    cp ./mimeapps.list "$HOME/.config/mimeapps.list"
    ln -s "$HOME/.config/mimeapps.list" "$HOME/.local/share/applications/mimeapps.list"
}

function tmux() {
    mkdir -p "$HOME/.config/tmux/"
    cp ./tmux.conf "$HOME/.config/tmux/"
}

function gdb() {
    mkdir -p "$HOME/.config/gdb/"
    cp ./gdbinit "$HOME/.config/gdb/"
}

function gtk() {
    mkdir -p "$HOME/.config/gtk-3.0/"
    cp ./settings.ini "$HOME/.config/gtk-3.0/"
}

function qt() {
    mkdir -p "$HOME/.config/qt6ct/"
    cp ./qt6ct.conf "$HOME/.config/qt6ct/qt6ct.conf"
}

function okular() {
    mkdir -p "$HOME/.config"
    cp ./okularrc "$HOME/.config/okularrc"
}

function flameshot() {
    mkdir -p "$HOME/.config/flameshot/"
    cp ./flameshot.ini "$HOME/.config/flameshot/"
}

function dunst() {
    mkdir -p "$HOME/.config/dunst/"
    cp ./dunstrc "$HOME/.config/dunst/"
}

function ccache() {
    mkdir -p "$HOME/.config/ccache/"
    cp ./ccache.conf "$HOME/.config/ccache/"
}

function glade() {
    mkdir -p "$HOME/.config/"
    cp ./glade.conf "$HOME/.config/"
}

function zsh() {
    cp ./.zshrc ./.zprofile "$HOME"
    chsh -s /usr/bin/zsh >/dev/null
    sudo chsh -s /usr/bin/zsh >/dev/null
}

function vscode() {
    mkdir -p "$HOME/.config/Code - OSS/User/"

    cp ./extensions.json \
        ./keybindings.json \
        ./settings.json \
        "$HOME/.config/Code - OSS/User/"
}

function xorg() {
    cp "./.xinitrc" "$HOME/.xinitrc"

    mkdir -p "/etc/X11/xorg.conf.d"
    sudo cp "./00-keyboard.conf" "/etc/X11/xorg.conf.d"
    sudo cp "./30-touchpad.conf" "/etc/X11/xorg.conf.d"
    sudo cp ./user-dirs.dirs "$HOME/.config/user-dirs.dirs"
}

function mpv() {
    mkdir -p "$HOME/.config/mpv/"
    cp ./input.conf ./mpv.conf "$HOME/.config/mpv/"
}

function wallpaper() {
    mkdir -p "$HOME/.local/share/wallpapers/"
    cp ./map.jpg "$HOME/.local/share/wallpapers/"
}

function qemu() {
    if ! sudo virsh net-info --network default | grep "Active:.*yes" >/dev/null 2>&1; then
        echo -e "$GRN==>$CLR enabling virsh default"
        sudo virsh net-start default >/dev/null 2>&1
        sudo virsh net-autostart default >/dev/null 2>&1
    fi

    # uncomment lines in libvirtd.conf
    lines=(
        'unix_sock_group = "libvirt"'
        'unix_sock_rw_perms = "0770"'
    )
    for line in "${lines[@]}"; do
        sudo sed -i "/$line/s/^#//" /etc/libvirt/libvirtd.conf
    done
}

function emoji_font() {
    sudo cp ./twemoji.ttf /usr/share/fonts/
    sudo cp ./75-twemoji.conf /etc/fonts/conf.d/75-twemoji.conf
}

function creds() {
    mkdir -p "$HOME/.ssh"
    mkdir -p "$HOME/.gnupg"

    cp ./.gitconfig \
        ./.gpgkey.asc \
        ./.pgpkey.asc \
        ./.pam-gnupg \
        "$HOME/"

    cp ./id_ed25519 \
        ./id_ed25519.pub \
        ./printfdebugging \
        ./printfdebugging.pub \
        ./cool \
        ./cool.pub \
        ./config \
        "$HOME/.ssh"

    cp ./gpg-agent.conf \
        ./gpg.conf \
        "$HOME/.gnupg"

    echo -e "$GRN==>$CLR decrypting credentials"
    while true; do
        ansible-vault decrypt \
            "$HOME/.gitconfig" \
            "$HOME/.gpgkey.asc" \
            "$HOME/.pgpkey.asc" \
            "$HOME/.pam-gnupg" \
            "$HOME/.gnupg/gpg-agent.conf" \
            "$HOME/.gnupg/gpg.conf" \
            "$HOME/.ssh/id_ed25519" \
            "$HOME/.ssh/id_ed25519.pub" \
            "$HOME/.ssh/printfdebugging" \
            "$HOME/.ssh/printfdebugging.pub" \
            "$HOME/.ssh/cool" \
            "$HOME/.ssh/cool.pub" \
            "$HOME/.ssh/config" >/dev/null 2>&1 && break
    done

    gpg --import "$HOME/.pgpkey.asc" >/dev/null 2>&1

    chown -R "$(whoami)" "$HOME/.gnupg"
    find "$HOME/.gnupg" -type f -exec chmod 600 {} \;
    find "$HOME/.gnupg" -type d -exec chmod 700 {} \;

    # get ssh keys for github and gitlab
    servers=(
        'github.com'
        'gitlab.com'
    )
    for server in "${servers[@]}"; do
        ssh-keyscan -t rsa "$server" >>"$HOME/.ssh/known_hosts"
    done
}

function autogen() {
    if [ -d "/media/projects/core" ]; then
        cp ./autogen.input "/media/projects/core/autogen.input"
    fi
}

function mirrorlist() {
    if curl -s http://127.0.0.1:9000/ | grep -qE 'core/|extra/|multilib/|lastsync|lastupdate'; then
        sudo cp ./mirrorlist /etc/pacman.d/mirrorlist
        sudo cp ./pacman.conf /etc/pacman.conf
        sudo systemctl mask reflector.service
    fi
}

function nginx() {
    sudo cp ./nginx.conf /etc/nginx/nginx.conf
}

function pacman_mirror() {
    local_folder=/media/external/archlinux
    remote_mirror=rsync://de.arch.mirror.kescher.at/mirror/arch/

    rsync -rlv \
        --exclude '/archive' \
        --exclude '/community' \
        --exclude '/community-staging' \
        --exclude '/community-testing' \
        --exclude '/core-debug' \
        --exclude '/core-staging' \
        --exclude '/core-staging-debug' \
        --exclude '/core-testing' \
        --exclude '/core-testing-debug' \
        --exclude '/extra-debug' \
        --exclude '/extra-staging' \
        --exclude '/extra-staging-debug' \
        --exclude '/extra-testing' \
        --exclude '/extra-testing-debug' \
        --exclude '/gnome-unstable' \
        --exclude '/gnome-unstable-debug' \
        --exclude '/images' \
        --exclude '/iso' \
        --exclude '/kde-unstable' \
        --exclude '/kde-unstable-debug' \
        --exclude '/latest' \
        --exclude '/multilib-debug' \
        --exclude '/multilib-staging' \
        --exclude '/multilib-staging-debug' \
        --exclude '/multilib-testing' \
        --exclude '/multilib-testing-debug' \
        --exclude '/other' \
        --exclude '/pool/packages-debug' \
        --exclude '/staging' \
        --exclude '/testing' \
        --exclude '/wsl' \
        "${remote_mirror}" \
        "${local_folder}"
}

function drives() {
    declare -A external=(
        [UUID]=6a90a7e3-3732-4b58-8a3a-fbc098a86b7e
        [PATH]=/media/external/
        [TYPE]=ext4
        [OPTIONS]='defaults 0 0'
    )

    declare -A personal=(
        [UUID]=18bd0da1-8e29-4d5a-a3bf-4cf8a012699d
        [PATH]=/media/personal/
        [TYPE]=ext4
        [OPTIONS]='defaults 0 0'
    )

    declare -A projects=(
        [UUID]=379872b5-a96a-4d1f-ad83-231cc27b7c6a
        [PATH]=/media/projects/
        [TYPE]=ext4
        [OPTIONS]='defaults 0 0'
    )

    declare -A archive=(
        [UUID]=4313c35d-7d9e-4e77-871e-7c70fdd1e01d
        [PATH]=/media/archive/
        [TYPE]=ext4
        [OPTIONS]='defaults 0 0'
    )

    drives=(
        external
        projects
        personal
        archive
    )

    modified=false
    for drive_name in "${drives[@]}"; do
        declare -n drive="$drive_name"
        if ! [ -d "${drive[PATH]}" ]; then
            sudo mkdir -p "${drive[PATH]}"
            sudo chown "$(whoami):$(whoami)" "${drive[PATH]}"
        fi

        [ "$(lsblk -f | grep -c "${drive[UUID]}")" -eq 0 ] && continue
        if [ "$(grep -e "${drive[UUID]}" /etc/fstab)" == "" ]; then
            echo "UUID=${drive[UUID]}    ${drive[PATH]}     ${drive[TYPE]}     ${drive[OPTIONS]}" | sudo tee -a /etc/fstab
            modified=true
        fi

        [ "$modified" ] && sudo mount -a
    done
}

mirrorlist &&
    packages &&
    aur &&
    services &&
    groups &&
    creds &&
    passwords &&
    pam &&
    drives &&
    git &&
    autogen &&
    suckless &&
    browser &&
    neovim &&
    tmux &&
    gdb &&
    gtk &&
    qt &&
    okular &&
    flameshot &&
    dunst &&
    ccache &&
    glade &&
    zsh &&
    vscode &&
    xorg &&
    mpv &&
    wallpaper &&
    emoji_font &&
    libreoffice_autogen &&
    nginx &&
    qemu
