- name: (okular) copy config file
  become: false
  tags:
    - okular
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.config/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - okularpartrc
    - okularrc

- name: (okular) save config file
  become: false
  tags:
    - save-okular
  ansible.builtin.copy:
    src: /home/{{ansible_user}}/.config/{{ item }}
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/okular/files/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - okularpartrc
    - okularrc
