- name: copy files to ~/.local/share
  become: false
  tags:
    - wallpapers
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.local/share
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - wallpapers
    - icons
