- name: (xorg) install packages
  tags:
    - xorg
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - xorg-server
    - xorg-xinit
    - xorg-xrandr
    - xorg-setxkbmap
    - xorg-xset
    - xcompmgr
    - xwallpaper
    - xclip
    - xsel
    - xorg-xauth
    - xorg-xprop
