- name: install xorg-server and surrounding packages
  tags:
    - xorg
    - packages
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-setxkbmap
      - xorg-xset

      - xcompmgr
      - xwallpaper
      - xclip
      - xsel
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: copy .xinitrc file
  become: false
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: .xinitrc
    dest: /home/{{ ansible_user }}/.xinitrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
