- name: (xorg) install packages
  tags:
    - xorg
    - packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - xorg
    - xcompmgr
    - xwallpaper
    - xclip
    - xsel

- name: (xorg) copy xinitrc
  become: false
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: .xinitrc
    dest: /home/{{ ansible_user }}/.xinitrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: (xorg) create conf.d directory
  become: true
  tags:
    - xorg
    - files
  ansible.builtin.file:
    path: "/etc/X11/xorg.conf.d"
    state: directory
    owner: "root"
    group: "root"

- name: (xorg) copy 30-touchpad.conf file
  become: true
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    owner: "root"
    group: "root"
    mode: 0644

- name: (xorg) copy 00-keyboard.conf file
  become: true
  tags:
    - xorg
    - files
  ansible.builtin.copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: "root"
    group: "root"
    mode: 0644

- name: (xorg) save xinitrc
  become: false
  tags:
    - save
    - save-xorg
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.xinitrc
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/xorg/files/.xinitrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
