- name: include distribution tasks
  tags:
    - vscode
    - include
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: (vscode) create config directory
  become: false
  tags:
    - vscode
  file:
    path: /home/{{ ansible_user }}/.config/Code - OSS/User
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (vscode) copy config files
  become: false
  tags:
    - vscode
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/home/{{ ansible_user }}/.config/Code - OSS/User/{{ item }}'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - extensions.json
    - keybindings.json
    - settings.json

- name: (vscode) save config files
  become: false
  tags:
    - save-vscode
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/home/{{ ansible_user }}/.config/Code - OSS/User/{{ item }}'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - extensions.json
    - keybindings.json
    - settings.json
