- name: include distribution tasks
  tags:
    - bluetooth
    - include
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: (bluetooth) add user to network group
  tags:
    - bluetooth
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: bluetooth
    append: true
