- name: (pip) install pip
  tags:
    - pip
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - python
    - python3-pip

- name: (pip) install pip packages
  become: false
  tags:
    - pip
    - packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    break_system_packages: true
  loop:
    - gtimelog
