- name: include distribution tasks
  tags:
    - creds
    - include
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: (creds) create ssh directory
  become: false
  tags:
    - creds
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/.ssh"
    state: directory
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: (creds) create personal public key
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ public_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519.pub"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"

- name: (creds) create personal private key
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ private_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0600"

- name: (creds) create work public key
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ public_work_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/cool.pub"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"

- name: (creds) create work private key
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ private_work_ssh_key_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/cool"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0600"

- name: (creds) create ssh config file
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ ssh_config_file }}"
    dest: "/home/{{ ansible_user }}/.ssh/config"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"

- name: (creds) create git config file
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ git_config_file }}"
    dest: "/home/{{ ansible_user }}/.gitconfig"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"

- name: (creds) create gpg key file
  become: false
  tags:
    - creds
  ansible.builtin.copy:
    content: "{{ gpg_key_file }}"
    dest: "/home/{{ ansible_user }}/.gpgkey.asc"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"
