- name: Install ZSH and Additional Packages
  tags: ["zsh", "packages"]
  community.general.pacman:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-completions
      - zsh-autosuggestions
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  # become: true

- name: Setup ZSH as system shell
  tags: ["zsh", "setup"]
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  become: true
  loop:
    - root
    - "{{ ansible_user }}"

- name: Copy ZSH Config Files
  tags: ["zsh", "files"]
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/{{ item }}
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0644
  loop:
    - .zshrc
    - .zprofile
