- name: (zsh) install packages
  tags:
    - zsh
    - packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - zsh-antigen
