- name: (zsh@voidlinux) install packages
  tags:
    - zsh
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - zsh
    - zsh-syntax-highlighting
    - zsh-completions
    - zsh-autosuggestions
