- name: include tasks
  tags:
    - gtk
    - include
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution|lower }}.yml"

- name: (gtk) create config directory
  become: false
  tags:
    - gtk
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/gtk-3.0"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (gtk) copy config file
  become: false
  tags:
    - gtk
    - files
  ansible.builtin.copy:
    src: settings.ini
    dest: /home/{{ ansible_user }}/.config/gtk-3.0/settings.ini
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (gtk) copy config file to etc
  become: true
  tags:
    - gtk
    - files
  ansible.builtin.copy:
    src: settings.ini
    dest: /etc/gtk-3.0/settings.ini
    owner: root
    group: root
    mode: 0755
