- name: (gtk) copy Adwaita theme to default theme
  become: true
  tags:
    - bootstrap
    - gtk
    - files
  ansible.builtin.copy:
    src: /usr/share/icons/Adwaita/
    dest: /usr/share/icons/default/
    owner: root
    group: root
    remote_src: true

- name: (gtk) install gtk related packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - gdk-pixbuf
    - lxappearance

- name: (gtk) copy config file to etc
  become: true
  tags:
    - bootstrap
    - gtk
    - files
  ansible.builtin.copy:
    src: settings.ini
    dest: /etc/gtk-3.0/settings.ini
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (gtk) extract tar.xz themes
  become: true
  tags:
    - bootstrap
    - gtk
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - Nordic-darker.tar.xz

- name: (gtk) install tar.xz themes
  become: true
  tags:
    - bootstrap
    - gtk
    - files
  ansible.builtin.shell: |
    if [ ! -d /usr/share/themes/{{ item }} ]; then
      cd /tmp 
      tar -xf {{ item }}.tar.xz 
      mv {{ item }} /usr/share/themes
    fi
  loop:
    - Nordic-darker
