- name: (gtk) copy Adwaita theme to default theme
  become: true
  tags:
    - gtk
    - files
  ansible.builtin.copy:
    src: /usr/share/icons/Adwaita/
    dest: /usr/share/icons/default/
    owner: root
    group: root
    remote_src: true

- name: (gtk) reinstall gdk-pixbuf
  community.general.xbps:
    name: gdk-pixbuf
    state: latest
