- name: (gtk) install gtk related packages
  tags:
    - gtk
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - gdk-pixbuf
    - lxappearance
    - breeze-icons

