- name: (libreoffice-dev) install packages
  tags:
    - libreoffice-dev
    - packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - build-essential
    - zip
    - ccache
    - junit4
    - libkrb5-dev
    - nasm
    - graphviz
    - python3
    - python3-dev
    - python3-setuptools
    - qtbase5-dev
    - libkf5coreaddons-dev
    - libkf5i18n-dev
    - libkf5config-dev
    - libkf5windowsystem-dev
    - libkf5kio-dev
    - libqt5x11extras5-dev
    - autoconf
    - libcups2-dev
    - libfontconfig1-dev
    - gperf
    - openjdk-17-jdk
    - doxygen
    - libxslt1-dev
    - xsltproc
    - libxml2-utils
    - libxrandr-dev
    - libx11-dev
    - bison
    - flex
    - libgtk-3-dev
    - libgstreamer-plugins-base1.0-dev
    - libgstreamer1.0-dev
    - ant
    - ant-optional
    - libnss3-dev
    - libavahi-client-dev
    - libxt-dev

- name: (git) clone the git repo
  become: false
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.git:
    repo: https://gerrit.libreoffice.org/core
    dest: /home/{{ ansible_user }}/repos/libreoffice
    update: no
    recursive: false

- name: (libreoffice-dev) copy autogen.input
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.copy:
    src: autogen.input
    dest: /home/{{ ansible_user }}/repos/libreoffice/autogen.input
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (libreoffice-dev) setup ccache with 100Gs
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.shell:
    cmd: |
      ccache --max-size=100G
