- name: include distribution tasks
  tags:
    - libreoffice-dev
    - include
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: (git) clone the git repo
  become: false
  tags:
    - libreoffice-dev
  ansible.builtin.git:
    repo: https://gerrit.libreoffice.org/core
    dest: /home/{{ ansible_user }}/repos/libreoffice
    update: no
    recursive: false

- name: (libreoffice-dev) copy autogen.input
  tags:
    - libreoffice-dev
  ansible.builtin.copy:
    src: autogen.input
    dest: /home/{{ ansible_user }}/repos/libreoffice/autogen.input
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (libreoffice-dev) copy glade.conf
  tags:
    - libreoffice-dev
  ansible.builtin.copy:
    src: glade.conf
    dest: /home/{{ ansible_user }}/.config/glade.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
