- name: (libreoffice-dev) install dependencies
  tags:
    - libreoffice-dev
    - packages
  community.general.zypper:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - autoconf
    - automake
    - bison
    - make
    - gcc
    - gcc-c++
    - cups-devel
    - fontconfig-devel
    - gperf
    - java-17-openjdk-devel
    - libxslt-devel
    - python3-devel
    - krb5-devel
    - libX11-devel
    - libXext-devel
    - libICE-devel
    - libSM-devel
    - libXt-devel
    - libXrender-devel
    - libXrandr-devel
    - flex
    - gtk3-devel
    - gstreamer-devel
    - gstreamer-plugins-base-devel
    - ant
    - junit
    - nasm
    - ccache
    - binutils-gold
    - mozilla-nss-devel
    - clang
    - llvm
    - clang-devel
    - llvm-devel

- name: (git) clone the git repo
  become: false
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.git:
    repo: https://gerrit.libreoffice.org/core
    dest: /home/{{ ansible_user }}/repos/libreoffice
    update: no
    recursive: false

- name: (libreoffice-dev) copy autogen.input
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.copy:
    src: autogen.suse
    dest: /home/{{ ansible_user }}/repos/libreoffice/autogen.input
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (libreoffice-dev) setup ccache with 100Gs
  tags:
    - libreoffice-dev
    - files
  ansible.builtin.shell:
    cmd: |
      ccache --max-size=100G
