- name: (libreoffice-dev) install dependencies
  tags:
    - libreoffice-dev
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - zlib-devel
    - libjpeg-turbo-devel
    - clucene-devel
    - expat-devel
    - xmlsec1-devel
    - nss-devel
    - nspr-devel
    - librevenge-devel
    - libodfgen-devel
    - libepubgen-devel
    - libwpd-devel
    - libwpg-devel
    - libwps-devel
    - libvisio-devel
    - libcdr-devel
    - libmspub-devel
    - libmwaw-devel
    - libetonyek-devel
    - libfreehand-devel
    - libe-book-devel
    - libabw-devel
    - libpagemaker-devel
    - libqxp-devel
    - libzmf-devel
    - libstaroffice-devel
    - lcms2-devel
    - libcppunit-devel
    - freetype-devel
    - libxslt-devel
    - libgcrypt-devel
    - libxml2-devel
    - python3-devel
    - libcurl-devel
    - boost-devel
    - mdds
    - frozen
    - glm
    - unixodbc-devel
    - libldap-devel
    - sane-devel
    - icu-devel
    - liborcus-devel
    - graphite-devel
    - harfbuzz-devel
    - libargon2-devel
    - redland-devel
    - hunspell-devel
    - zxcvbn-c-devel
    - zxing-cpp-devel
    - box2d-devel
    - hyphen-devel
    - mythes-devel
    - CoinMP-devel
    - lpsolve-devel
    - libexttextcat-devel
    - libnumbertext-devel
    - libepoxy-devel
    - cairo-devel
    - liblangtag-devel
    - libpng-devel
    - tiff-devel
    - libwebp-devel
    - fontconfig-devel
    - libcmis-devel
    - gobject-introspection
    - libgirepository-devel
    - libglib-devel
    - openssl-devel
    - libXrender-devel
    - libbluetooth-devel
    - gpgmepp-devel
    - libXinerama-devel
    - libXt-devel
    - libX11-devel
    - libICE-devel
    - libSM-devel
    - libopenjpeg2-devel
    - abseil-cpp-devel
    - poppler-cpp-devel
    - gtk+3-devel
    - gtk4-devel
    - gst-plugins-base1-devel
    - qt6-base-devel
    - qt6-multimedia-devel
    - qt5-qmake
    - qt5-devel
    - kf6-kio-devel
    - kf6-frameworkintegration-devel
    - libmariadbclient-devel
    - postgresql-libs-devel
    - libfbclient3-devel
    - libatomic_ops-devel
    - automake
    - flex
    - gperf
    - hyphen
    - icu
    - libtool
    - openldap
    - which
    - gettext
    - xz
    - tar
    - perl-Archive-Zip
    - pkg-config
    - sane
    - unzip
    - zip
    - python3-setuptools
    - fontforge
    - python3-lxml
    - qt6-base
    - gnupg
    - glib-devel
    - openjdk17
    - apache-ant
    - beanshell
    - rhino
    - hsqldb1.8.0
    - llvm18
    - llvm18-devel
    - nasm
    - ccache
