
color0 #1B2229
color1 #ff6c6b
color2 #98be65
color3 #ECBE7B
color4 #51afef
color5 #c678dd
color6 #46D9FF
color7 #DFDFDF

color8 #3f444a
color9 #ff6655
color10 #99bb66
color11 #ECBE7B
color12 #51afef
color13 #c678dd
color14 #46D9FF
color15 #dfdfdf

background #282c34 
foreground #d8dee9

# Font settings
font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

enable_audio_bell no
enable_visual_bell no

map ctrl+1 send_text all \033[49;5u
map ctrl+2 send_text all \033[50;5u
map ctrl+3 send_text all \033[51;5u
map ctrl+4 send_text all \033[52;5u
map ctrl+5 send_text all \033[53;5u
map ctrl+6 send_text all \033[54;5u
map ctrl+7 send_text all \033[55;5u
map ctrl+8 send_text all \033[56;5u
map ctrl+9 send_text all \033[57;5u
map ctrl+shift+t send_text all \033[84;6u
