- name: install flameshot on archlinux
  tags:
    - flameshot
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - flameshot
