- name: (flameshot) install packages
  tags:
    - flameshot
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - flameshot

- name: (flameshot) create config directory
  become: false
  tags:
    - flameshot
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/flameshot"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (flameshot) copy config file
  become: false
  tags:
    - flameshot
    - files
  ansible.builtin.copy:
    content: "{{ flameshot_config_file }}"
    dest: /home/{{ ansible_user }}/.config/flameshot/flameshot.ini
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
