- name: (flameshot) include archlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: arch.yml
  when: ansible_os_family == "Archlinux"

- name: (flameshot) include voidlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: void.yml
  when: ansible_os_family == "Void"

- name: (flameshot) create config directory
  become: false
  tags:
    - flameshot
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/flameshot"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (flameshot) copy config file
  become: false
  tags:
    - flameshot
    - files
  ansible.builtin.copy:
    content: "{{ flameshot_config_file }}"
    dest: /home/{{ ansible_user }}/.config/flameshot/flameshot.ini
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
