- name: (git@archlinux) install packages
  tags:
    - git
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - git
    - openssh
