- name: make sure git is installed
  community.general.pacman:
    name: git
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: ensure ~/repos exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/repos
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: ensure ~/downloads exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/downloads
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: clone git repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    update: no
  become: false ## maybe it was executing as root otherwise
  loop:
    [
      {
        repo: "{{ my_github_handle }}/printfdebugging.git",
        path: "/home/{{ ansible_user }}/repos/printfdebugging",
      },
      {
        repo: "{{ my_github_handle }}/dotfiles.git",
        path: "/home/{{ ansible_user }}/repos/dotfiles",
      },
      {
        repo: "{{ my_github_handle }}/interpreters.git",
        path: "/home/{{ ansible_user }}/repos/interpreters",
      },
      {
        repo: "{{ my_github_handle }}/lua-embedding.git",
        path: "/home/{{ ansible_user }}/repos/lua-embedding",
      },
      {
        repo: "{{ my_github_handle }}/notes.git",
        path: "/home/{{ ansible_user }}/repos/notes",
      },
      {
        repo: "{{ my_github_handle }}/files.git",
        path: "/home/{{ ansible_user }}/repos/files",
      },
      {
        repo: "{{ my_github_handle }}/ray-tracing-in-one-weekend.git",
        path: "/home/{{ ansible_user }}/repos/ray-tracing-in-one-weekend",
      },
      {
        repo: "{{ my_github_handle }}/brave.git",
        path: "/home/{{ ansible_user }}/.config/BraveSoftware/Brave-Browser",
      },
      {
        repo: "{{ my_github_handle }}/thunderbird.git",
        path: "/home/{{ ansible_user }}/.thunderbird",
      },
    ]
