- name: (git) install packages
  tags:
    - git
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - openssh

- name: (git) create gitconfig
  tags:
    - git
    - files
  copy:
    content: "{{ git_config_file }}"
    dest: "/home/{{ ansible_user }}/.gitconfig"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0644"
  become: false

- name: (git) create repos directory
  become: false
  tags:
    - git
    - files
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/repos
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (git) create downloads directory
  become: false
  tags:
    - git
    - files
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/downloads
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (git) github rsa key
  become: false
  tags:
    - git
    - files
  ansible.builtin.lineinfile:
    dest: /home/{{ ansible_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: (git) clone git repositories
  become: false
  tags:
    - git
    - files
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    update: no
  loop:
    [

      # basic repositories
      { repo: "{{ my_github_handle }}/chromium.git",                              path: "/home/{{ ansible_user }}/.config/chromium", },
      { repo: "{{ my_github_handle }}/thunderbird.git",                           path: "/home/{{ ansible_user }}/.thunderbird", },

      # other repositores
      { repo: "{{ my_github_handle }}/site",                                      path: "/home/{{ ansible_user }}/repos/site", },
      { repo: "{{ my_github_handle }}/files.git",                                 path: "/home/{{ ansible_user }}/repos/files", },
      { repo: "{{ my_github_handle }}/dotfiles.git",                              path: "/home/{{ ansible_user }}/repos/dotfiles", },
      { repo: "{{ my_github_handle }}/libreoffice-theme-template.git",            path: "/home/{{ ansible_user }}/repos/libreoffice-theme-template", },
      { repo: "{{ my_github_handle }}/icecream-parlour-management-system.git",    path: "/home/{{ ansible_user }}/repos/icecream-parlour-management-system", },
      { repo: "{{ my_github_handle }}/geometry-wars.git",                         path: "/home/{{ ansible_user }}/repos/geometry-wars", },
      { repo: "{{ my_github_handle }}/interpreters.git",                          path: "/home/{{ ansible_user }}/repos/interpreters", },
      { repo: "{{ my_github_handle }}/bouncing-shapes.git",                       path: "/home/{{ ansible_user }}/repos/bouncing-shapes", },
      { repo: "{{ my_github_handle }}/learn-opengl.git",                          path: "/home/{{ ansible_user }}/repos/learn-opengl", },
      { repo: "{{ my_github_handle }}/sfml-blueprints.git",                       path: "/home/{{ ansible_user }}/repos/sfml-blueprints", },
      { repo: "{{ my_github_handle }}/win32-qt-comparison.git",                   path: "/home/{{ ansible_user }}/repos/win32-qt-comparison", },
      { repo: "{{ my_github_handle }}/nullptr.git",                               path: "/home/{{ ansible_user }}/repos/nullptr", },
      { repo: "{{ my_github_handle }}/project-earth.git",                         path: "/home/{{ ansible_user }}/repos/project-earth", },
    ]
