- name: install dunst on Archlinux
  tags:
    - dunst
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - libnotify
    - dunst

- name: ensure config directory exists
  become: false
  tags:
    - dunst
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/dunst"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: copy the config files
  become: false
  tags:
    - dunst
    - files
  ansible.builtin.copy:
    src: dunstrc
    dest: /home/{{ ansible_user }}/.config/dunst/dunstrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: copy back config files from ~/.config/dunst
  become: false
  tags:
    - save
    - save-dunst
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/dunst/{{ item }}
    dest: "/home/{{ ansible_user }}/repos/dotfiles/roles/dunst/files/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - dunstrc
