- name: (dunst@archlinux) install packages
  tags:
    - dunst
    - packages
  community.general.pacman:
    name:
      - "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - dunst
