- name: (dunst@voidlinux) install packages
  tags:
    - dunst
    - packages
  community.general.xbps:
    name:
      - "{{ item }}"
    state: latest
  loop:
    - dunst

- name: (dunst) create config directory
  become: false
  tags:
    - dunst
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/dunst"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (dunst) copy config file
  become: false
  tags:
    - dunst
    - files
  ansible.builtin.copy:
    src: dunstrc
    dest: /home/{{ ansible_user }}/.config/dunst/dunstrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (dunst) save config file
  become: false
  tags:
    - save
    - save-dunst
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/dunst/dunstrc
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/dunst/files/dunstrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

