#!/usr/bin/python3
"""
Script to run rlTimeLog from the source checkout without installing
"""
import os
import sys

basedir = os.path.dirname(os.path.realpath(__file__))
pkgdir = os.path.join(basedir, 'src')
sys.path.insert(0, pkgdir)

from gtimelog.rltimelog import main  # noqa: E402

main()
