- name: (emacs@archlinux) install packages
  tags:
    - emacs
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - emacs-nativecomp
    - ttf-iosevka-nerd
    - fd
