- name: install emacs-nativecomp on archlinux
  tags:
    - emacs
    - packages
  community.general.pacman:
    name: emacs-nativecomp
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

# - name: ensure config directory exists
#   become: false
#   tags:
#     - emacs
#     - files
#   ansible.builtin.file:
#     path: "/home/{{ ansible_user }}/.config/emacs"
#     state: directory
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: "0755"

# - name: copy emacs config files
#   become: false
#   tags:
#     - emacs
#     - files
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: /home/{{ ansible_user }}/.config/emacs/{{ item }}
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0755
#   loop:
#     - init.el
#     - config.org

- name: copy doom emacs configuration
  become: false
  tags:
    - emacs
    - files
  ansible.builtin.copy:
    src: doom
    dest: /home/{{ ansible_user }}/.config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
# for  the time being, I will install doom emacs manually, and will
# decide later on what to do
