- name: (emacs) include archlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: arch.yml
  when: ansible_os_family == "Archlinux"

- name: (emacs) include voidlinux tasks
  tags:
    - include
  ansible.builtin.include_tasks:
    file: void.yml
  when: ansible_os_family == "Void"

- name: (emacs) create config directory
  become: false
  tags:
    - emacs
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/emacs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (emacs) copy config file
  become: false
  tags:
    - emacs
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.config/emacs/{{ item }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - init.el
    - config.org

- name: (emacs) copy snippets
  become: false
  tags:
    - emacs
    - files
  ansible.builtin.copy:
    src: "snippets"
    dest: /home/{{ ansible_user }}/.config/emacs
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (emacs) save config files
  become: false
  tags:
    - save
    - save-emacs
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/emacs/{{ item }}
    dest: "/home/{{ ansible_user }}/repos/dotfiles/roles/emacs/files/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - init.el
    - config.org

- name: (emacs) save snippets
  become: false
  tags:
    - save
    - save-emacs
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/emacs/snippets
    dest: "/home/{{ ansible_user }}/repos/dotfiles/roles/emacs/files"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
