- name: (emacs) install packages
  tags:
    - emacs
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - emacs-x11

- name: (emacs) copy config files
  become: false
  tags:
    - emacs
    - files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ ansible_user }}/.config/emacs/{{ item }}
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  loop:
    - init.el
    - config.org
    - snippets

- name: (emacs) save config files
  become: false
  tags:
    - save
    - save-emacs
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/emacs/{{ item }}
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/emacs/files
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  loop:
    - init.el
    - config.org
    - snippets
