- name: copy scripts to the ~/.local/bin folder
  ansible.builtin.copy:
    src: bin
    dest: /home/{{ ansible_user }}/.local
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
