- name: (bin) copy shell-scripts 
  become: false
  tags:
    - bin
    - files
  ansible.builtin.copy:
    src: bin
    dest: /home/{{ ansible_user }}/.local
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (bin) save shell-scripts
  become: false
  tags:
    - save
    - save-bin
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.local/bin
    dest: "/home/{{ ansible_user }}/personal/dotfiles/roles/bin/files/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
