- name: (gtimelog) install packages
  become: true
  tags:
    - gtimelog
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - libsoup-devel

- name: (gtimelog) install gtimelog
  become: true
  tags:
    - gtimelog
  ansible.builtin.pip:
    name: "{{ item }}"
    break_system_packages: true
  loop:
    - gtimelog
