- name: (gtimelog) install packages
  become: true
  tags:
    - gtimelog
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - libsoup-devel

- name: (gtimelog) create a symlink to gtimelog
  become: true
  tags:
    - gtimelog
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/repos/gtimelog/gtimelog"
    dest: /usr/local/bin/gtimelog
    state: link
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0755"
