- name: include tasks
  tags:
    - gtimelog
    - include
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution|lower }}.yml"

- name: (gtimelog) install gtimelog
  become: true
  tags:
    - gtimelog
    - files
  ansible.builtin.shell:
    cmd: |
      cd /home/{{ ansible_user }}/repos/gtimelog
      ./setup.py install
