- name: install tmux
  community.general.pacman:
    name: tmux
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: Ensure the tmux configuration directory exists
  file:
    path: /home/{{ ansible_user }}/.config/tmux
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: yes

- name: install tpm package manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{ ansible_user }}/.tmux/plugins/tpm

- name: copy the config file to ~/.config/tmux
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/{{ ansible_user }}/.config/tmux/tmux.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
