- name: install tmux
  tags:
    - tmux
    - packages
  community.general.pacman:
    name: tmux
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: Ensure the tmux configuration directory exists
  become: false
  tags:
    - tmux
    - files
  file:
    path: /home/{{ ansible_user }}/.config/tmux
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: clone tpm package manager
  become: false
  tags:
    - tmux
    - files
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{ ansible_user }}/.tmux/plugins/tpm
    update: false

- name: copy the config file to ~/.config/tmux
  become: false
  tags:
    - tmux
    - files
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/{{ ansible_user }}/.config/tmux/tmux.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: copy back tmux config file from ~/.config/tmux
  become: false
  tags:
    - save
    - save-tmux
  ansible.builtin.copy:
    src: /home/{{ansible_user}}/.config/tmux/tmux.conf
    dest: /home/{{ ansible_user }}/repos/dotfiles/roles/tmux/files/tmux.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
