- name: ensure yt-dlp is installed
  tags:
    - yt-dlp
    - packages
  community.general.pacman:
    name: yt-dlp
    state: latest

- name: ensure config directory exists
  become: false
  tags:
    - yt-dlp
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/yt-dlp"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: copy config files to ~/.config/yt-dlp
  become: false
  tags:
    - yt-dlp
    - files
  ansible.builtin.copy:
    src: config
    dest: /home/{{ ansible_user }}/.config/yt-dlp/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
