- name: (cool) install dependencies
  tags:
    - cool
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - libcap-devel
    - libcap-ng-devel
    - libpng-devel
    - poco-devel
    - cpputest
    - nodejs
    - chromium
    - python3-lxml
    - python3-polib
    - pam-devel

- name: (cool) clone the git repo
  become: false
  tags:
    - cool
  ansible.builtin.git:
    repo: git@github.com:printfdebugging/online.git
    dest: /home/{{ ansible_user }}/repos/online
    update: no
    recursive: false

- name: (cool) set upstream in the online repository
  tags:
    - cool
  ansible.builtin.shell:
    cmd: |
      cd "/home/{{ ansible_user }}/repos/online"
      [ $(git remote -v | grep "upstream" | wc -l) -ne 0 ] && git remote remove upstream
      git remote add upstream https://github.com/CollaboraOnline/online.git
