- name: (base@archlinux) allow sudo without passwd
  tags:
    - aur
    - packages
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00_{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    mode: 0644
    validate: "visudo -cf %s"

- name: (base@archlinux) install aur helper
  become: false
  tags:
    - aur
    - packages
  ansible.builtin.shell:
    cmd: |
      cd /tmp
      git clone https://aur.archlinux.org/yay-bin
      cd yay-bin
      makepkg -si --noconfirm

- name: (base@archlinux) install packages
  become: false
  tags:
    - aur
    - packages
  ansible.builtin.shell:
    cmd: |
      /usr/bin/yay -S {{ item }} --noconfirm
  loop:
    - chromium
    - visual-studio-code-bin
    - ttf-twemoji
    - par
    - thunderbird
    - lua
    - cmake # need to learn it
    - ansible
    - neofetch
    - man-db
    - btop
    - vim
    - pasystray
    - pavucontrol
    - unzip
    - network-manager-applet
    - python-pexpect
    - ripgrep
    - dolphin
    - breeze-icons
    - ocean-sound-theme
    - go
    - xdotool
    - netcat
    - python-watchdog
    - libreoffice-fresh
    - loupe
    - bear
    - zola
    - mtpfs
    - gvfs-mtp
    - mpv
    - python-pip
    - evince
    - okular
    - gdb
    - ntfs-3g
    - obs-studio
    - glade
    - kitty
    - luarocks
    - imagemagick
    - dunst
    - xcompmgr
    - discord
    - picom
    - qemu-desktop
    - quickemu
    - qt5-styleplugins
    - qt5ct
    - apple-fonts
    - ruff
    - ruff-lsp
    - i3lock-fancy
    - sfml
    - glfw
    - vulkan-radeon
    - vulkan-devel
    - glm
    - shaderc
    - element-desktop-nightly
    - gimp
    - xf86-video-amdgpu
    - xf86-video-ati

- name: (base@archlinux) copy twemoji fontconfig
  become: true
  tags:
    - aur
    - packages
  ansible.builtin.copy:
    src: /usr/share/fontconfig/conf.avail/75-twemoji.conf
    dest: /etc/fonts/conf.d/75-twemoji.conf
    owner: root
    group: root
    mode: 0644

- name: (base@archlinux) revoke sudo without passwd
  become: true
  tags:
    - aur
    - packages
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00_{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    state: absent
    validate: "visudo -cf %s"
