- name: (base) install apt packages
  tags:
    - base
    - packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - thunderbird
    - par
    - lua5.3
    - cmake
    - ansible
    - neofetch
    - man-db
    - btop
    - vim
    - pasystray
    - pavucontrol
    - pulseaudio
    - unzip
    - network-manager
    - network-manager-applet
    - ripgrep
    - dolphin
    - xdotool
    - netcat-openbsd
    - python3-watchdog
    - libreoffice
    - bear
    - mtp-tools
    - gvfs
    - mpv
    - pip
    - evince
    - okular
    - gdb
    - ntfs-3g
    - obs-studio
    - glade
    - luarocks
    - qt5-style-plugins
    - qt5ct
    - i3lock-fancy
    - libsfml-dev
    - libglfw3-dev
    - libglm-dev
    - vulkan-tools
    - glslc
    - vulkan-validationlayers
    - spirv-tools
    - libvulkan-dev
    - libxxf86vm-dev
    - gimp
    - yarn
    - wget
    - curl
    - fontconfig
    - clang-16
    - clang-tools-16
    - gtypist
    - ueberzug
    - xauth
    - command-not-found

- name: (base) upgrade distribution
  tags:
    - base
    - packages
  ansible.builtin.apt:
    upgrade: true

- name: (base) add user to network group
  tags:
    - base
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: network
    append: true
