- name: (base) install packages
  tags:
    - base
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - thunderbird
    - vscode
    - par
    - lua
    - cmake
    - extra-cmake-modules
    - ansible
    - neofetch
    - man-db
    - btop
    - vim-huge
    - pasystray
    - pavucontrol
    - pulseaudio
    - unzip
    - NetworkManager
    - network-manager-applet
    - ripgrep
    - Thunar
    - tumbler-plugins-extra
    - breeze-icons
    - adwaita-icon-theme
    - go
    - xdotool
    - xprop
    - netcat
    - python3-watchdog
    - libreoffice
    - loupe
    - Bear
    - zola
    - mtpfs
    - mpv
    - python3-pip
    - okular
    - gdb
    - rr
    - perf
    - ntfs-3g
    - obs
    - glade3
    - luarocks
    - ImageMagick
    - libmagick-devel
    - qt5-styleplugins
    - qt5ct
    - ruff
    - i3lock-fancy
    - SFML-devel
    - glfw-devel
    - mesa-vulkan-radeon
    - Vulkan-Tools
    - vulkan-loader-devel
    - libXxf86vm-devel
    - glm
    - shaderc
    - gimp
    - xf86-video-amdgpu
    - xf86-video-ati
    - xf86-input-libinput
    - yarn
    - wget
    - curl
    - fontconfig
    - clang-tools-extra18
    - libnma
    - gtypist
    - ueberzug
    - xauth
    - pyright
    - xtools
    - git-review
    - fzf
    - fd
    - figlet
    - figlet-fonts
    - lolcat-c
    - seahorse
    - valgrind
    - ctags
    - sxiv
    - feh
    - openjdk

- name: (base) upgrade distribution
  tags:
    - base
    - packages
  community.general.xbps:
    upgrade: true

- name: (base) add user to network group
  tags:
    - base
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: network
    append: true

- name: (base) create downloads directory
  become: false
  tags:
    - base
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/downloads"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (base) create .config directory
  become: false
  tags:
    - base
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (base) copy user-dirs.dirs file
  tags:
    - base
    - files
  ansible.builtin.copy:
    src: user-dirs.dirs
    dest: /home/{{ ansible_user }}/.config/user-dirs.dirs
    owner: root
    group: root
    mode: 0644

- name: (base) install fonts
  become: false
  tags:
    - base
    - fonts
    - packages
  ansible.builtin.shell:
    cmd: |
      if [ ! -d "/home/{{ ansible_user }}/.local/share/fonts" ]; then
        mkdir -p /home/{{ ansible_user }}/.local/share/fonts
      fi

      cd /home/{{ ansible_user }}/.local/share/fonts/

      if [ ! -d "/home/{{ ansible_user }}/.local/share/fonts/{{ item.font }}.zip" ]; then
        curl -LO {{ item.url }}
      fi

      if [ ! -d "/home/{{ ansible_user }}/.local/share/fonts/{{ item.font }}" ]; then
        unzip {{ item.font }}.zip -d {{ item.font }}
      fi
  loop:
    [
      { font: "FiraCode",     url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip", },
    ]

- name: (base) copy twemoji font file
  become: false
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: twemoji
    dest: /home/{{ ansible_user }}/.local/share/fonts
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (base) copy twemoji fontconfig
  become: true
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: 75-twemoji.conf
    dest: /etc/fonts/conf.d/75-twemoji.conf
    owner: root
    group: root
    mode: 0644
