- name: (base) install packages
  tags:
    - base
    - packages
  community.general.zypper:
    name: "{{ item }}"
    state: latest
  loop:
    - MozillaFirefox
    - MozillaThunderbird
    - par
    - lua
    - cmake
    - ansible
    - neofetch
    - man
    - btop
    - vim
    - pasystray
    - pavucontrol
    - pulseaudio
    - unzip
    - NetworkManager
    - ripgrep
    - thunar
    - go
    - xdotool
    - xprop
    - netcat
    - python3-watchdog
    - libreoffice
    - loupe
    - zola
    - mtp-tools
    - gvfs
    - mpv
    - evince
    - okular
    - gdb
    - ntfs-3g
    - lua53-luarocks
    - ImageMagick
    - libMagick++-devel
    - ruff
    - Bear
    - glade
    - libsfml2-2_6
    - libglfw-devel
    - vulkan-validationlayers
    - vulkan-tools
    - vulkan-devel
    - vulkan-utility-libraries-devel
    - libXxf86vm-devel
    - glm-devel
    - shaderc
    - gimp
    - xf86-video-amdgpu
    - xf86-video-ati
    - xf86-input-libinput
    - yarn
    - wget
    - curl
    - fontconfig
    - clang-tools
    - libnma
    - gtypist
    - ueberzugpp
    - xauth

- name: (base) install fonts
  become: true
  tags:
    - base
    - packages
  ansible.builtin.shell:
    cmd: |
      if [ $(fc-list | grep "{{ item.font }}" | wc -l) -eq 0 ]; then
        mkdir -p ~/.local/tmp
        cd ~/.local/tmp
        curl -LO {{ item.url }}
        unzip {{ item.font }}.zip -d {{ item.font }}
        cp -r {{ item.font }} /usr/share/fonts
      fi
  loop:
    [
      { font: "Iosevka",         url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Iosevka.zip", },
    ]

- name: (base) copy twemoji font file
  become: true
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: twemoji
    dest: /usr/share/fonts
    owner: root
    group: root
    mode: 0644

- name: (base) copy twemoji fontconfig
  become: true
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: 75-twemoji.conf
    dest: /etc/fonts/conf.d/75-twemoji.conf
    owner: root
    group: root
    mode: 0644

- name: (base) upgrade distribution
  tags:
    - base
    - packages
  community.general.zypper:
    name: '*'
    state: latest
