- name: (base) install packages
  tags:
    - base
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - thunderbird
    - vscode
    - par
    - lua
    - cmake
    - extra-cmake-modules
    - ansible
    - neofetch
    - man-db
    - man-pages
    - man-pages-devel
    - man-pages-posix
    - btop
    - vim-huge
    - pasystray
    - pavucontrol
    - pulseaudio
    - unzip
    - NetworkManager
    - ripgrep
    - Thunar
    - tumbler-plugins-extra
    - go
    - xdotool
    - xprop
    - netcat
    - python3-watchdog
    - libreoffice
    - loupe
    - Bear
    - zola
    - mtpfs
    - mpv
    - okular
    - gdb
    - rr
    - perf
    - ntfs-3g
    - obs
    - glade3
    - luarocks
    - qt5-styleplugins
    - qt5ct
    - ruff
    - i3lock-fancy
    - SFML-devel
    - glfw-devel
    - mesa-vulkan-radeon
    - Vulkan-Tools
    - vulkan-loader-devel
    - libXxf86vm-devel
    - glm
    - shaderc
    - gimp
    - xf86-video-amdgpu
    - xf86-video-ati
    - xf86-input-libinput
    - yarn
    - wget
    - curl
    - fontconfig
    - clang-tools-extra18
    - libnma
    - gtypist
    - ueberzug
    - xauth
    - pyright
    - xtools
    - git-review
    - fzf
    - fd
    - figlet
    - figlet-fonts
    - lolcat-c
    - seahorse
    - valgrind
    - ctags
    - sxiv
    - feh
    - openjdk

- name: (base) upgrade distribution
  tags:
    - base
    - packages
  community.general.xbps:
    upgrade: true

- name: (base) add user to network group
  tags:
    - base
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: network
    append: true
