- name: (base@voidlinux) install packages
  tags:
    - base
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - chromium
    - vscode
    - par
    - thunderbird
    - lua
    - cmake
    - ansible
    - neofetch
    - man-db
    - btop
    - vim
    - pasystray
    - pavucontrol
    - pulseaudio
    - unzip
    - NetworkManager
    - network-manager-applet
    - ripgrep
    - dolphin
    - breeze-icons
    - adwaita-icon-theme
    - go
    - xdotool
    - xprop
    - netcat
    - python3-watchdog
    - libreoffice
    - loupe
    - Bear
    - zola
    - mtpfs
    - gvfs-mtp
    - mpv
    - python-pip
    - evince
    - okular
    - gdb
    - ntfs-3g
    - obs
    - glade3
    - luarocks
    - ImageMagick
    - qt5-styleplugins
    - qt5ct
    - ruff
    - i3lock-fancy
    - SFML-devel
    - glfw-devel
    - mesa-vulkan-radeon
    - vulkan-loader-devel
    - libXxf86vm-devel
    - glm
    - shaderc
    - gimp
    - xf86-video-amdgpu
    - xf86-video-ati
    - xf86-input-libinput
    - yarn
    - wget
    - curl
    - fontconfig
    - clang-tools-extra18
    - libnma

- name: (base@voidlinux) install ttf-iosevka-nerd 
  become: true
  tags:
    - base
    - packages
  ansible.builtin.shell:
    cmd: |
      if [ $(fc-list | grep "Iosevka" | wc -l) -eq 0 ]; then
        mkdir -p ~/.local/tmp
        cd ~/.local/tmp
        curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Iosevka.zip
        unzip Iosevka.zip -d Iosevka
        cp -r Iosevka /usr/share/fonts
      fi

- name: (base@voidlinux) install ttf-jetbrainsmono-nerd
  become: true
  tags:
    - base
    - packages
  ansible.builtin.shell:
    cmd: |
      if [ $(fc-list | grep "JetBrainsMono" | wc -l) -eq 0 ]; then
        mkdir -p ~/.local/tmp
        cd ~/.local/tmp
        curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
        unzip JetBrainsMono.zip -d JetBrainsMono
        cp -r JetBrainsMono /usr/share/fonts
      fi

- name: (base@voidlinux) copy twemoji font file
  become: true
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: twemoji
    dest: /usr/share/fonts
    owner: root
    group: root
    mode: 0644

- name: (base@voidlinux) copy twemoji fontconfig
  become: true
  tags:
    - base
    - packages
  ansible.builtin.copy:
    src: 75-twemoji.conf
    dest: /etc/fonts/conf.d/75-twemoji.conf
    owner: root
    group: root
    mode: 0644

- name: (base@voidlinux) upgrade distribution
  tags:
    - base
    - packages
  community.general.xbps:
    upgrade: true

- name: (base@voidlinux) add user to network group
  tags:
    - base
    - system
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: network
    append: true
