- name: install alacritty on Archlinux
  community.general.pacman:
    name: alacritty
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: ensure config directory exists
  become: true
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/alacritty"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: copy the config files
  ansible.builtin.copy:
    src: alacritty.toml
    dest: /home/{{ ansible_user }}/.config/alacritty/alacritty.toml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
