- name: (gpg) install packages
  tags:
    - gpg
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - gnupg2

- name: (gpg) create config directory
  become: false
  tags:
    - gpg
    - files
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.gpg"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: (gpg) copy config file
  become: false
  tags:
    - gpg
    - files
  ansible.builtin.copy:
    content: "{{ lookup('vars', item.content) }}"
    dest: /home/{{ ansible_user }}/.gpg/{{ item.file }}
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  loop:
    [
      { content: "printfdebugging_gmail_com_public_asc",            file: "printfdebugging@gmail.com.public.asc", },
      { content: "printfdebugging_gmail_com_private_asc",           file: "printfdebugging@gmail.com.private.asc", },
      { content: "sahil_gautam_extern_allotropia_de_private_asc",   file: "sahil.gautam.extern@allotropia.de.private.asc", },
      { content: "sahil_gautam_extern_allotropia_de_public_asc",    file: "sahil.gautam.extern@allotropia.de.public.asc", },
    ]
