- name: (awesome@archlinux) install awesome
  tags:
    - awesome
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - awesome
