- name: (awesome) install awesome
  tags:
    - awesome
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
  loop:
    - awesome

- name: (awesome) copy config files
  become: false
  tags:
    - awesome
    - files
  ansible.builtin.copy:
    src: awesome
    dest: /home/{{ ansible_user }}/.config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: (awesome) save config files
  become: false
  tags:
    - save
    - save-awesome
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/.config/awesome
    dest: "/home/{{ ansible_user }}/repos/dotfiles/roles/awesome/files/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
