- name: install neovim and dependencies
  tags:
    - neovim
    - packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"
  loop:
    - neovim
    - git
    - npm
