- name: install neovim and dependencies
  tags: ["neovim", "packages"]
  community.general.pacman:
    name:
      - neovim
      - git
      - npm
    state: latest
    extra_args: "--nodeps --noconfirm --overwrite '*'"

- name: copy config files to ~/.config
  tags: ["neovim", "files"]
  copy:
    src: nvim
    dest: /home/{{ ansible_user }}/.config
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: 0755
