- name: (neovim@voidlinux) install packages
  tags:
    - neovim
    - packages
  community.general.xbps:
    name: "{{ item }}"
    state: latest
    upgrade: true
  loop:
    - neovim
    - git
    - nodejs
