- name: include distribution tasks
  tags:
    - fonts
    - include
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: (fonts) copy twemoji font file
  become: true
  tags:
    - fonts
  ansible.builtin.copy:
    src: twemoji
    dest: /usr/share/fonts
    owner: root
    group: root
    mode: 0644

- name: (fonts) copy twemoji fontconfig
  become: true
  tags:
    - fonts
  ansible.builtin.copy:
    src: 75-twemoji.conf
    dest: /etc/fonts/conf.d/75-twemoji.conf
    owner: root
    group: root
    mode: 0644
